config/routes.rb
Rails.application.routes.draw do
  get 'user/edit'
  devise_for :users
  get 'questions/index'
  get 'comments/index'
  root to: "questions#index"
  resources :users ,only:[:edit, :update]
  resources :questions,only:[:index,:new, :create,:show,:destroy] do
    resources :comments, only: :create
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :answer,presence: true
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :users
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :explain
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :questions 
         has_many :comment

         with_options presence: true do
          validates :nickname
          validates :profile
        end
end

app/models/user_question.rb
class UserQuestion < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  private
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:nickname,:profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment=Comment.new(comment_params)
    if Obscenity.profane?(@comment.answer)
      @comment.answer="不適切な表現が含まれています"
    end
    @comment.save
    redirect_to "/questions/#{@comment.question_id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:answer).merge(user_id: current_user.id, question_id: params[:question_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  def index
    @question=Question.all
  end

  def new
    @question=Question.new
  end

  def create
    @question=Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @question=Question.find(params[:id])
    @comment=Comment.new
    @comments= @question.comments.includes(:user)
  end

  def destroy
    @question=Question.find(params[:id])
    @question.destroy
    redirect_to root_path
  end
  
  private
  def question_params
    params.require(:question).permit(:title,:explain).merge(user_id: current_user.id)
  end
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:nickname, :email, :profile)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper

  def convert_url_to_a_element(text)
    uri_reg = URI.regexp(%w[http https])
    text.gsub(uri_reg) { %{<a href="#{$&}">#{$&}</a>} }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question/index.html.erb
<h1>Question</h1>
<%#render  heder%>
<% unless user_signed_in? %>
<%= link_to "Sign up", new_user_registration_path, class: 'btn'%>
<%= link_to "Sign in", user_session_path, class: 'btn'%>
<% else %>
<%= link_to 'ログアウト',  destroy_user_session_path, method: :delete, class: 'btn'  %>
<%= link_to current_user.nickname,  edit_user_path(current_user),  class: 'btn'  %>
<%= link_to "質問をする",root_path %>
<% end %>

app/views/questions/index.html.erb
<div class='main_page'>
  <div class='main_header'>
  <div class='app_name'>Questweet</div>
  <%#render  heder%>
  <% unless user_signed_in? %>
  <div class='user_menu'>
    <%= link_to "Sign up", new_user_registration_path, class: 'btn'%>
    <%= link_to "Sign in", user_session_path, class: 'btn'%>
  </div>
    <% else %>
  <div class='user_menu'>
    <%= link_to 'ログアウト',  destroy_user_session_path, method: :delete, class: 'btn'  %> 
    <%= link_to current_user.nickname,  edit_user_path(current_user),  class: 'btn'  %>
    <%= link_to "質問をする",new_question_path ,  class: 'btn'%> 
  </div>
  <% end %>
</div>
<div class='question_list'>QUESTION LIST</div>
<% @question.each do |question|  %>
<p><%= link_to question.title , question_path(question),  class: 'question_btn'%></p>
<% end %>

app/views/questions/new.html.erb
<h2>Question </h2>
<%= form_with model: @question, local: true do |f| %>
<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autocomplete: true %>
  </div>

  <div class="field">
    <%= f.label :explain %><br />
    <%= f.text_area :explain, autocomplete: true %>
  </div>
   
   <%= f.submit class: 'chat-room-form__action-btn'%>
 <% end %>

app/views/questions/show.html.erb
<div class='show_main'>

  <div class='show_titel'><%=  @question.title %> </div>
    <div class='show_explain_header'>＜質問詳細＞</div>
      <div class='show_explain'><%=  @question.explain %> </div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@question, @comment], local: true) do |form| %>
        <%= form.text_area :answer, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
          <% if current_user.id == @question.user_id %>
            <%= link_to "質問を削除する",question_path(@question), method: :delete %>
          <% end %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <%= link_to "質問一覧に戻る" ,root_path%>

    

    <div class="comments">
      <h4>＜みんなの回答一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.nickname %>：</strong>
          <%= auto_link(comment.answer, html: { target: '_blank' }) %> 
           
        </p>
        
      <% end %>
      
    </div>


  </div>
  
  </div>

app/views/users/edit.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :profile%>
          </div>
          <div class='field-input'>
            <%= f.text_field :profile, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :profile%>
          </div>
          <div class='field-input'>
            <%= f.text_field :profile, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>